---

# ansible_controller/meta/main.yml

# http://docs.ansible.com/playbooks_roles.html#role-dependencies
galaxy_info:
  author: your name
  description: 
  company: your company (optional)
  # Some suggested licenses:
  # - BSD (default)
  # - MIT
  # - GPLv2
  # - GPLv3
  # - Apache
  # - CC-BY
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2

#dependencies: 
# Dependinces for external repos seems broken for now.
# Should be able to replace ansible-librarian with the following some day.
  # - { role: 'git+http://github.com/geerlingguy/ansible-role-elasticsearch-curator' }
  # - { galaxy: "geerlingguy.elasticsearch-curator", role: elasticsearch-curator }
  # - { galaxy: "geerlingguy.logstash", role_name: logstash }
  # - { galaxy: "geerlingguy.kibana", role: kibana, role_name: kibana }
  # List your role dependencies here, one per line. Only
  # dependencies available via galaxy should be listed here.
  # Be sure to remove the '[]' above if you add dependencies
  # to this list.
  
